FROM node:22-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json ./
COPY apps/api/package.json apps/api/package.json
COPY apps/dashboard/package.json apps/dashboard/package.json
COPY apps/demo-shop/package.json apps/demo-shop/package.json
COPY packages/browser-sdk/package.json packages/browser-sdk/package.json
RUN npm ci
COPY tsconfig.base.json ./
COPY packages/browser-sdk packages/browser-sdk
COPY apps/demo-shop apps/demo-shop
ARG VITE_CRASHLENS_API_URL=http://localhost:4000
ARG VITE_CRASHLENS_API_KEY=crashlens_demo_key_12345
ENV VITE_CRASHLENS_API_URL=$VITE_CRASHLENS_API_URL
ENV VITE_CRASHLENS_API_KEY=$VITE_CRASHLENS_API_KEY
RUN npm run build:sdk && npm run build --workspace @crashlens/demo-shop

FROM nginx:1.27-alpine AS runtime
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/apps/demo-shop/dist /usr/share/nginx/html
EXPOSE 8080
